package com.usguri.health_hub.physician;

public enum Specialty {
    CARDIOLOGY,
    DERMATOLOGY,
    ENDOCRINOLOGY,
    GASTROENTEROLOGY,
    GERIATRICS,
    GYNECOLOGY,
    HEMATOLOGY,
    NEPHROLOGY,
    NEURORADIOLOGY,
    OBSTETRICS,
    PEDIATRICS,
    PSYCHIATRY,
    RHEUMATOLOGY,
    UROLOGY

}
