export const SPECIALTIES = [
  "CARDIOLOGY",
  "DERMATOLOGY",
  "ENDOCRINOLOGY",
  "GASTROENTEROLOGY",
  "GERIATRICS",
  "GYNECOLOGY",
  "HEMATOLOGY",
  "NEPHROLOGY",
  "NEURORADIOLOGY",
  "OBSTETRICS",
  "PEDIATRICS",
  "PSYCHIATRY",
  "RHEUMATOLOGY",
  "UROLOGY",
]

export type Specialty =
  | "CARDIOLOGY"
  | "DERMATOLOGY"
  | "ENDOCRINOLOGY"
  | "GASTROENTEROLOGY"
  | "GERIATRICS"
  | "GYNECOLOGY"
  | "HEMATOLOGY"
  | "NEPHROLOGY"
  | "NEURORADIOLOGY"
  | "OBSTETRICS"
  | "PEDIATRICS"
  | "PSYCHIATRY"
  | "RHEUMATOLOGY"
  | "UROLOGY";
