name: Format Javascript code
on:
  pull_request:
    branches: ["main"]
    paths: ["frontend/**"]

jobs:
  prettier:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write .
