name: Format Java code
on:
  pull_request_review:
    types: [submitted]
    branches: ["main"]
    paths: ["backend/**"]

jobs:
  googleformat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-sorting-imports --replace"
          version: 1.17.0
