name: Format Java code
on:
  pull_request:
    branches: ["main"]
    paths: ["backend/**"]

jobs:
  googleformat:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Run Google Java Format
        run: |
          # Install Google Java Format
          curl -sL https://github.com/google/google-java-format/releases/download/v1.17.0/google-java-format-1.17.0-all-deps.jar \
            --output google-java-format.jar
          # Find Java files in the repository and format
          find . -name "*.java" | xargs -I {} java -jar google-java-format.jar --replace {}
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: "Tubias Java Formatter"
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
